before:
  hooks:
    - go mod tidy

gomod:
  proxy: true

builds:
- env:
    - CGO_ENABLED=0
  goos:
    - linux
    - darwin
    - windows
  goarch:
    - amd64
    - arm64
  flags:
    - -trimpath
  ldflags:
    - -s -w -X main.Version={{.Version}}
