before:
  hooks:
    - go mod tidy

gomod:
  proxy: true

builds:
- env:
    - CGO_ENABLED=0
  goos:
    - linux
    - darwin
    - windows
  goarch:
    - amd64
    - arm64
  flags:
    - -trimpath
  ldflags:
    - -s -w -X main.Version={{.Version}}

brews:
  - homepage: https://github.com/jamescun/httplog
    description: httplog is a command line tool that logs HTTP requests
    license: MIT
    folder: Formula
    commit_author:
      name: James Cunningham
      email: git@jamescun.com
    tap:
      owner: jamescun
      name: homebrew-formulas
      token: "{{ .Env.TAP_GITHUB_TOKEN }}"
